-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: May 05, 2023 at 12:01 AM
-- Server version: 10.4.27-MariaDB
-- PHP Version: 8.2.0

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `webproject`
--

-- --------------------------------------------------------

--
-- Table structure for table `book_form`
--

CREATE TABLE `book_form` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `phone` varchar(255) NOT NULL,
  `address` varchar(255) NOT NULL,
  `location` varchar(255) NOT NULL,
  `guests` int(255) NOT NULL,
  `arrivals` date NOT NULL,
  `leaving` date NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `book_form`
--

INSERT INTO `book_form` (`id`, `name`, `email`, `phone`, `address`, `location`, `guests`, `arrivals`, `leaving`) VALUES
(1, 'ghida', 'gh@gmail.com', '12345', 'lebanon', 'ksa', 8, '2023-05-10', '2023-05-24'),
(2, 'bahaa', 'bahaa@gmail.com', '7898765456', 'lebanon', 'japan', 4, '2023-05-05', '2023-05-25'),
(3, 'nm', 'nm@gmail.com', '4578', 'lebanon', 'USA', 2, '2023-05-10', '2023-05-17'),
(4, 'asdcasc', 'fg@gmail.com', '23456', 'lebanon', 'asdfgh', 7, '2023-05-17', '2023-05-23'),
(5, 'mimi', 'mimi@gmail.com', '966567890345', 'riyadh', 'lebanon', 3, '2023-05-10', '2023-05-20');

-- --------------------------------------------------------

--
-- Table structure for table `category`
--

CREATE TABLE `category` (
  `id` int(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `image` varchar(255) NOT NULL,
  `description` longtext NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `category`
--

INSERT INTO `category` (`id`, `name`, `image`, `description`) VALUES
(1, 'India', 'images/india.jpg', 'Explore the Land of Diversity - Discover Hidden Gems of India'),
(2, 'France', 'images/france.jpg', 'Discover More of France: Beyond the City of Love'),
(3, 'Canada', 'images/canada.jpg', 'Explore the Great Outdoors and More: Travel to Canada'),
(4, 'USA', 'images/usa.jpg', 'The Land of Possibilities: Experience the Best of USA Travel'),
(5, 'Egypt', 'images/egypt.jpg', 'Journey to the Land of Pharaohs: Unveil the Wonders of Egypt'),
(6, 'Japan', 'images/japan.jpg', 'Discover the Magic of Japan: Where Tradition Meets Innovation'),
(7, 'Jordan', 'images/jordan.jpg', 'Step into History: Travel to Jordan and Explore the Wonders of Petra'),
(8, 'Lebanon', 'images/lebanon.jpg', 'Experience the Beauty of Lebanon: A Hidden Gem of the Middle East'),
(9, 'China', 'images/china.jpg', 'Explore the Ancient and Modern Wonders of China'),
(10, 'UAE', 'images/uae.jpg', 'Discover the Glamour of the UAE: A Fusion of Modernity and Tradition'),
(11, 'Peru', 'images/peru.jpg', 'Discover the Mysteries of Peru: From the Andes to the Amazon'),
(12, 'Greece', 'images/greece.jpg', 'Island-Hopping in Greece: Discover the Charm of the Greek Islands');

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE `products` (
  `id` int(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `image` varchar(255) NOT NULL,
  `description` longtext NOT NULL,
  `newprice` varchar(255) NOT NULL,
  `oldprice` varchar(255) NOT NULL,
  `map` longtext NOT NULL,
  `details` longtext NOT NULL,
  `catid` int(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`id`, `name`, `image`, `description`, `newprice`, `oldprice`, `map`, `details`, `catid`) VALUES
(1, 'Taj Mahal', 'images/imga-1.jpg', 'Discover the iconic beauty and symbolic power of the Taj Mahal, India\'s most beloved and enchanting monument!', '$90.00', '$120.00', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3549.400402283334!2d78.03956727463745!3d27.175149548764683!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39747121d702ff6d%3A0xdd2ae4803f767dde!2sTaj%20Mahal!5e0!3m2!1sen!2slb!4v1682976102588!5m2!1sen!2slb', 'The Taj Mahal is a stunning white marble mausoleum located in Agra, India. Built by the Mughal emperor Shah Jahan in memory of his beloved wife Mumtaz Mahal, it is considered one of the most beautiful buildings in the world and is a UNESCO World Heritage Site.<br>\r\n<br>\r\nConstruction of the Taj Mahal began in 1632 and took over 20 years to complete, with the help of an estimated 20,000 artisans and workers. The structure features intricate carvings and inlaid work made of precious stones, including jade, crystal, lapis lazuli, and turquoise. The building is also known for its impressive dome, which is over 70 feet high and topped with a finial made of gold.<br>\r\n<br>\r\nVisitors to the Taj Mahal can take a guided tour of the interior and exterior of the building, as well as the surrounding gardens and reflecting pools. The mausoleum is open from sunrise to sunset every day except Fridays, when it is closed for prayers. It is advisable to arrive early in the morning to avoid crowds and to see the Taj Mahal at its most beautiful, during sunrise.<br>\r\n<br>\r\nThe Taj Mahal is not only a beautiful building but also a symbol of love and devotion, as it was built by the emperor as a tribute to his beloved wife. It is a must-visit destination for anyone traveling to India and is sure to leave a lasting impression on all who see it.', 1),
(2, 'Jaipur', 'images/jaipur.jpg', 'Discover the vibrant colors and rich culture of Jaipur on a journey like no other!', '$75.00', '$90.00', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d455500.2051435601!2d75.19960043581878!3d26.884594447901716!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x396c4adf4c57e281%3A0xce1c63a0cf22e09!2sJaipur%2C%20Rajasthan%2C%20India!5e0!3m2!1sen!2slb!', 'Jaipur is a vibrant city in the Indian state of Rajasthan, known for its rich history, colorful culture, and stunning architecture. The city is also referred to as the \"Pink City\" due to the distinctive pink color of many of its buildings.<br>\r\n<br>\r\nOne of the must-visit attractions in Jaipur is the City Palace, which was built in the early 18th century and is a beautiful blend of Rajasthani and Mughal architecture. The palace complex includes courtyards, gardens, and several palatial buildings, which now house museums and galleries showcasing the city\'s art and cultural heritage.<br>\r\n<br>\r\nAnother popular attraction in Jaipur is the Hawa Mahal, also known as the Palace of Winds, which is a five-story pink sandstone building with over 900 windows. The structure was built in the late 18th century to allow royal women to watch street processions without being seen by the public.\r\n<br><br>\r\nJaipur is also home to several historic forts and palaces, including the Amber Fort, a massive fortress built in the 16th century that offers stunning views of the surrounding landscape. The Nahargarh Fort and the Jaigarh Fort are also popular attractions for their impressive architecture and panoramic views.\r\n<br><br>\r\nFor those interested in shopping and handicrafts, Jaipur is famous for its colorful textiles, jewelry, and handicrafts. The city\'s bazaars and markets, including Johari Bazaar and Bapu Bazaar, are excellent places to find unique souvenirs and gifts.\r\n<br><br>\r\nOverall, Jaipur is a fascinating city that offers visitors a glimpse into Rajasthan\'s rich history and culture. Its stunning architecture, vibrant colors, and lively atmosphere make it a must-visit destination in India.', 1),
(3, 'Delhi', 'images/delhi.jpg', 'Uncover the fascinating history and diverse flavors of Delhi, a city that never fails to amaze!', '$80.00', '$95.00', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d448193.9510412846!2d76.7635645984973!3d28.644287350921363!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390cfd5b347eb62d%3A0x37205b715389640!2sDelhi%2C%20India!5e0!3m2!1sen!2slb!4v1682974056587!5', 'Delhi is the capital city of India and one of the most vibrant and bustling cities in the world. The city is a melting pot of cultures, with a rich history spanning over 2,500 years and a fascinating mix of ancient and modern architecture.\r\n<br><br>\r\nOne of the most iconic landmarks in Delhi is the Red Fort, a massive 17th-century fortress built by the Mughal emperor Shah Jahan. The fort\'s stunning red sandstone walls and intricate carvings make it a must-visit attraction for anyone interested in Indian history and architecture.\r\n<br><br>\r\nAnother popular destination in Delhi is the Qutub Minar, a towering minaret that is over 800 years old and one of the tallest brick towers in the world. The minaret is part of a larger complex that includes several other historic buildings, such as the Alai Darwaza and the Quwwat-ul-Islam Mosque.\r\n<br><br>\r\nFor those interested in religious sites, Delhi has several important temples, including the Lotus Temple, a stunning building shaped like a lotus flower, and the Akshardham Temple, which features stunning carvings and sculptures.\r\n<br><br>\r\nDelhi is also known for its vibrant street markets and bazaars, such as Chandni Chowk and Dilli Haat, which offer a wide range of goods, from traditional handicrafts to modern fashion and electronics.\r\n<br><br>\r\nFood lovers will also enjoy Delhi\'s vibrant food scene, with a wide variety of street food, traditional Indian cuisine, and international options available throughout the city.\r\n<br><br>\r\nOverall, Delhi is a fascinating city with something to offer everyone. Its rich history, stunning architecture, lively culture, and delicious food make it a must-visit destination for anyone traveling to India.', 1),
(4, 'Paris', 'images/img-2.jpg', 'Experience the romance and beauty of Paris, the City of Light, where art, culture, and history converge in a truly enchanting atmosphere!', '$100.00', '$150.00', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d83998.77824461092!2d2.264633890832824!3d48.85893843528405!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66e1f06e2b70f%3A0x40b82c3688c9460!2sParis%2C%20France!5e0!3m2!1sen!2slb!4v1682974087086!', 'Paris is the capital city of France and one of the most popular tourist destinations in the world. The city is known for its stunning architecture, world-class museums, vibrant culture, and romantic ambiance.\r\n<br><br>\r\nOne of the most famous landmarks in Paris is the Eiffel Tower, a massive wrought-iron structure that offers panoramic views of the city. Visitors can climb to the top of the tower or enjoy a meal at one of the restaurants located on the lower levels.\r\n<br><br>\r\nAnother popular attraction in Paris is the Louvre Museum, one of the largest and most famous art museums in the world. The Louvre is home to over 35,000 works of art, including the famous painting, the Mona Lisa.\r\n<br><br>\r\nParis is also known for its beautiful parks and gardens, such as the Luxembourg Gardens and the Tuileries Gardens. These green spaces offer a tranquil escape from the city and are perfect for a leisurely stroll or a picnic.\r\n<br><br>\r\nFor those interested in shopping, Paris is famous for its high-end fashion boutiques, including designer labels such as Chanel and Louis Vuitton. The city\'s department stores, such as Galeries Lafayette and Printemps, are also popular shopping destinations.\r\n<br><br>\r\nFood lovers will also enjoy Paris\'s vibrant culinary scene, which includes everything from traditional French cuisine to international fare. Visitors can enjoy a croissant and café au lait at a sidewalk café or dine in one of the city\'s many Michelin-starred restaurants.\r\n<br><br>\r\nOverall, Paris is a beautiful and vibrant city that offers something for everyone. Its stunning architecture, world-class museums, romantic ambiance, and delicious food make it a must-visit destination for travelers from around the world.', 2),
(5, 'Carcassonne', 'images/carcassonne.jpg', 'Step back in time and explore the enchanting medieval fortress of Carcassonne, where every stone has a story to tell', '$95.00', '$130.00', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d93058.44817028119!2d2.2666880737343926!3d43.20788465667064!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x12ae2c390116bd8b%3A0xe28fdf3b77a114c7!2s11000%20Carcassonne%2C%20France!5e0!3m2!1sen!2slb!', 'Carcassonne is a stunning fortified medieval city located in the south of France, and a popular destination for travelers looking to experience France\'s rich history and architecture.\r\n<br><br>\r\nThe city is surrounded by 3 kilometers of impressive stone walls and towers, and features narrow cobblestone streets lined with charming buildings that date back to the Middle Ages. The main attraction is the Castle and Ramparts of Carcassonne, a UNESCO World Heritage Site that has been beautifully restored to its former glory.\r\n<br><br>\r\nVisitors can explore the castle\'s many rooms and halls, learn about the city\'s history at the Carcassonne Museum, and take a walk along the ramparts to enjoy stunning views of the surrounding countryside. There are also several excellent restaurants and cafes within the city walls, offering a variety of traditional French dishes and wines.\r\n<br><br>\r\nCarcassonne is also surrounded by beautiful countryside, with rolling hills, vineyards, and charming small towns to explore. The Canal du Midi, a UNESCO World Heritage Site, is nearby and offers boat tours and bike rentals for visitors who want to explore the region.\r\n<br><br>\r\nOverall, Carcassonne is a unique and enchanting destination that is sure to captivate visitors with its medieval charm, rich history, and beautiful surroundings.', 2),
(6, 'Lyon', 'images/lyon.jpg', 'Indulge in the gastronomic capital of France and uncover the hidden gems of Lyon, where culture, cuisine, and history collide!', '$75.00', '$95.00', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d89076.99375964321!2d4.752728784756637!3d45.758040855533785!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47f4ea516ae88797%3A0x408ab2ae4bb21f0!2sLyon%2C%20France!5e0!3m2!1sen!2slb!4v1682974160651!', 'Lyon is a vibrant city located in the east of France and is known for its rich history, beautiful architecture, and culinary scene. The city is situated at the confluence of the Rhône and Saône rivers, offering stunning views and a relaxed atmosphere.\r\n<br><br>\r\nLyon is a UNESCO World Heritage Site, with a historic Old Town that features narrow cobblestone streets, beautiful Renaissance buildings, and stunning churches, such as the Basilica of Notre-Dame de Fourvière. Visitors can explore the Old Town\'s many charming squares and enjoy the local boutiques, cafes, and restaurants.\r\n<br><br>\r\nLyon is also famous for its culinary scene and is home to many Michelin-starred restaurants. Visitors can indulge in local specialties such as quenelles, saucisson, and coussin de Lyon, and explore the many food markets and specialty shops throughout the city.\r\n<br><br>\r\nThe city is also home to many museums and cultural attractions, such as the Musée des Confluences and the Musée des Beaux-Arts. The Parc de la Tête d\'Or, one of the largest urban parks in Europe, is also a popular destination for visitors and locals alike.\r\n<br><br>\r\nOverall, Lyon is a beautiful and vibrant city that offers a unique mix of history, culture, and gastronomy. Whether you\'re interested in exploring the city\'s many cultural attractions, dining at world-class restaurants, or simply enjoying the city\'s relaxed atmosphere, Lyon is a must-visit destination for any traveler to France.', 2),
(7, 'Niagara Falls', 'images/img-12.jpg', 'Behold the natural wonder and stunning beauty of Niagara Falls, where the power of water and breathtaking vistas leave a lasting impression!', '$130.00', '$160.00', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d186585.56645956624!2d-79.25284552731075!3d43.05406514764222!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89d3445eec824db9%3A0x46d2c56156bda288!2sNiagara%20Falls%2C%20ON%2C%20Canada!5e0!3m2!1sen!', 'Niagara Falls is a stunning natural wonder located on the border between the United States and Canada. The falls are made up of three different waterfalls - the American Falls, the Bridal Veil Falls, and the Horseshoe Falls - and are a popular tourist destination for visitors from around the world.\r\n<br><br>\r\nVisitors can view the falls from various vantage points, including observation decks, boat tours, and even helicopter rides. The Maid of the Mist boat tour takes visitors up close to the falls, allowing them to experience the powerful mist and thundering roar of the water.\r\n<br><br>\r\nIn addition to the falls themselves, there are many other attractions in the area. Visitors can explore the nearby Niagara Falls State Park on the American side, or visit the bustling tourist district on the Canadian side, which features casinos, restaurants, and souvenir shops.\r\n<br><br>\r\nFor those looking for a more adventurous experience, there are also opportunities for zip-lining, hiking, and other outdoor activities in the area.\r\n<br><br>\r\nOverall, Niagara Falls is a breathtaking natural wonder that offers a unique and unforgettable experience for visitors. Whether you\'re interested in scenic views, outdoor activities, or the local attractions, Niagara Falls is a must-see destination.', 3),
(8, 'Tofino', 'images/tofinoo.jpg', 'Escape to the breathtaking coastal beauty of Tofino, where the rugged wilderness meets the soothing waves and serenity awaits at every turn!', '$65.00', '$80.00', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d41772.29500811589!2d-125.92751264041142!3d49.12903283566059!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x548990ccb0093843%3A0x331095695a741a35!2sTofino%2C%20BC%2C%20Canada!5e0!3m2!1sen!2slb!4v16', 'Tofino is a charming coastal town located on the western edge of Vancouver Island, in British Columbia, Canada. The town is situated on the edge of the Pacific Ocean, and is surrounded by stunning natural beauty, including beautiful beaches, old-growth forests, and rugged coastline.\r\n<br><br>\r\nOne of the main attractions in Tofino is the stunning Long Beach, which stretches for more than 16 kilometers and offers visitors the chance to explore tidal pools, hike along the shoreline, or simply relax on the sandy beach. Visitors can also take a scenic boat tour to explore the nearby Clayoquot Sound, which is home to a wide variety of marine wildlife, including whales, seals, and sea otters.\r\n<br><br>\r\nFor those looking for a more active vacation, Tofino offers plenty of opportunities for outdoor activities, such as surfing, kayaking, and hiking. Visitors can explore the nearby Pacific Rim National Park Reserve, which offers a range of hiking trails and stunning vistas.\r\n<br><br>\r\nThe town itself is also a popular destination, with a charming local art scene, unique shops, and excellent restaurants serving fresh seafood and locally sourced ingredients. Visitors can also learn about the history and culture of the local First Nations communities by visiting the Tofino Tribal Parks Interpretive Centre.\r\n<br><br>\r\nOverall, Tofino is a beautiful and peaceful destination that offers a unique blend of natural beauty, outdoor activities, and local culture. Whether you\'re interested in exploring the beaches and forests, experiencing the local art scene, or simply relaxing in the quiet coastal town, Tofino is a must-visit destination.', 3),
(9, 'Vancouver', 'images/vancouver.jpg', 'Discover the dynamic and multicultural city of Vancouver, where urban adventure, natural beauty, and diverse communities blend seamlessly!', '$70.00', '$90.00', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d83327.37148291532!2d-123.20630508187014!3d49.25781819074317!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x548673f143a94fb3%3A0xbb9196ea9b81f38b!2sVancouver%2C%20BC%2C%20Canada!5e0!3m2!1sen!2slb!', 'Vancouver is a cosmopolitan coastal city located in western Canada, surrounded by mountains and the Pacific Ocean. Known for its stunning natural beauty, thriving cultural scene, and diverse population, Vancouver offers a wealth of experiences for visitors to enjoy.\r\n<br><br>\r\nOne of the city\'s most popular attractions is Stanley Park, an urban park that covers more than 400 hectares and offers a wide range of outdoor activities, including cycling, walking, and hiking. Visitors can also explore the Vancouver Aquarium, which is home to more than 50,000 animals, including sea otters, dolphins, and beluga whales.\r\n<br><br>\r\nVancouver is also known for its vibrant cultural scene, with a wide range of museums, art galleries, and cultural events. The Museum of Anthropology at the University of British Columbia is a must-visit destination for those interested in the art and culture of the Pacific Northwest\'s First Nations communities, while the Vancouver Art Gallery showcases a wide range of contemporary and historical art.\r\n<br><br>\r\nThe city is also famous for its food scene, which features a diverse range of cuisines, including fresh seafood, local produce, and international dishes. Visitors can explore the many restaurants and food markets throughout the city, and enjoy locally brewed craft beer and wine.\r\n<br><br>\r\nFor those looking for outdoor adventure, Vancouver offers plenty of opportunities for skiing, snowboarding, and hiking in the nearby mountains. The nearby Whistler Blackcomb ski resort is one of the largest and most popular ski resorts in North America, and offers world-class skiing and snowboarding.\r\n<br><br>\r\nOverall, Vancouver is a beautiful and dynamic city that offers a wide range of experiences for visitors to enjoy. Whether you\'re interested in exploring the outdoors, experiencing the local culture, or simply relaxing in the city\'s beautiful surroundings, Vancouver is a must-visit destination.', 3),
(10, 'Mount Rushmore', 'images/img-3.jpg', 'Explore American History At The Majestic Mount Rushmore In South Dakota.', '$75.00', '$95.00', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d11503.280200667057!2d-103.46910184487147!3d43.880279854034505!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x877d35dc6e0294dd%3A0x2c6d18a52a7b083d!2sMt%20Rushmore!5e0!3m2!1sen!2slb!4v1682974256628', 'Mount Rushmore National Memorial is a sculpture carved into the granite face of Mount Rushmore, located in the Black Hills region of South Dakota, United States. The sculpture features the heads of four American presidents - George Washington, Thomas Jefferson, Theodore Roosevelt, and Abraham Lincoln - and is one of the most iconic landmarks in the country.\r\n<br><br>\r\nVisitors to Mount Rushmore can view the sculpture from various vantage points, including a viewing platform at the base of the mountain and a scenic drive that winds through the park. The park also offers a range of outdoor activities, including hiking, fishing, and camping.\r\n<br><br>\r\nIn addition to the sculpture, there are many other attractions in the area, including the nearby Crazy Horse Memorial, which features a massive sculpture of the Lakota leader Crazy Horse. Visitors can also explore the nearby Black Hills National Forest, which offers stunning natural beauty and outdoor recreation opportunities.\r\n<br><br>\r\nThe park also offers a variety of educational programs and exhibits, including a museum that tells the story of the sculpture\'s creation and the history of the area. Visitors can learn about the lives and legacies of the four presidents depicted on the sculpture and the challenges faced by the sculptor, Gutzon Borglum, during the carving process.\r\n<br><br>\r\nOverall, Mount Rushmore is a stunning and iconic destination that offers a unique blend of natural beauty, American history, and outdoor recreation opportunities. Whether you\'re interested in exploring the sculpture, the surrounding area, or learning about the history of the United States, Mount Rushmore is a must-visit destination.', 4),
(11, 'Disney World', 'images/img-6.jpg', 'Get Ready For Magical Adventures At The Happiest Place On Earth - Disney World!', '$170.00', '$200.00', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3315.008402929625!2d-117.92154912508275!3d33.81209623037401!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80dcd7d12b3b5e6b%3A0x2ef62f8418225cfa!2sDisneyland%20Park!5e0!3m2!1sen!2slb!4v16829743045', 'Disneyland is a world-renowned theme park located in Anaheim, California. The park opened in 1955 and has since become a beloved destination for families and Disney enthusiasts from all over the world.\r\n<br><br>\r\nDisneyland is divided into eight themed lands, each with its own unique attractions, rides, and experiences. From the classic fairytale charm of Fantasyland to the futuristic thrills of Tomorrowland, there is something for everyone at the park.\r\n<br><br>\r\nSome of the most iconic rides and attractions at Disneyland include Pirates of the Caribbean, Haunted Mansion, Space Mountain, and It\'s a Small World. Visitors can also enjoy parades, live entertainment, and fireworks shows throughout the day and evening.\r\n<br><br>\r\nIn addition to the rides and attractions, Disneyland is known for its immersive theming and attention to detail. From the themed restaurants and shops to the character meet-and-greets, every aspect of the park is designed to transport visitors into the magical world of Disney.\r\n<br><br>\r\nThere are also several hotels located within walking distance of Disneyland, making it easy for visitors to fully immerse themselves in the park\'s atmosphere and enjoy multiple days of fun and entertainment.\r\n<br><br>\r\nOverall, Disneyland is a must-visit destination for anyone who loves Disney, theme parks, or just having fun with friends and family. With its combination of classic attractions, immersive theming, and endless entertainment options, Disneyland is a magical destination that truly has something for everyone.', 4),
(12, 'Hawaii', 'images/hawaii.jpg', 'Experience paradise in Hawaii, where natural beauty create the perfect escape!', '$90.00', '$120.00', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3828210.194277207!2d-160.14750053520018!3d20.445201358648692!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x7bffdb064f79e005%3A0x4b7782d274cc8628!2sHawaii%2C%20USA!5e0!3m2!1sen!2slb!4v168297450020', 'Hawaii is a beautiful tropical destination located in the central Pacific Ocean, made up of eight major islands that each offer a unique blend of natural beauty, rich culture, and outdoor activities.\r\n<br><br>\r\nOne of the main attractions of Hawaii is its stunning beaches, which are known for their crystal-clear waters, white sand, and year-round warm temperatures. Visitors can enjoy a wide range of water activities, including snorkeling, scuba diving, surfing, and paddleboarding.\r\n<br><br>\r\nHawaii is also home to several active volcanoes, including Kilauea, which has been continuously erupting since 1983. Visitors can explore the Hawaii Volcanoes National Park, which features hiking trails, scenic drives, and lava tubes that allow visitors to explore the volcanic landscape up close.\r\n<br><br>\r\nThe islands are also rich in culture and history, with a strong tradition of hula dancing, Hawaiian music, and storytelling. Visitors can attend traditional luaus, visit cultural centers, and learn about the history and customs of the Hawaiian people.\r\n<br><br>\r\nIn addition to the natural beauty and cultural attractions, Hawaii also offers a wide range of outdoor activities, including hiking, ziplining, and helicopter tours that provide stunning views of the islands from above.\r\n<br><br>\r\nOverall, Hawaii is a paradise for those seeking adventure, relaxation, and a unique cultural experience. With its stunning natural beauty, rich cultural traditions, and endless outdoor activities, Hawaii is a must-visit destination for anyone looking for a tropical escape.', 4),
(13, 'Giza Pyramids', 'images/img-4.jpg', 'Experience the wonder and mystery of the Giza Pyramids, a timeless testament to the ingenuity of Ancient Egypt', '$80.00', '$100.00', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d13824.344741457398!2d31.12235134380955!3d29.976953036654052!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14584587ac8f291b%3A0x810c2f3fa2a52424!2sThe%20Great%20Pyramid%20of%20Giza!5e0!3m2!1sen!2s', 'The Giza Pyramids are one of the most iconic landmarks in the world, located on the outskirts of Cairo, Egypt. The pyramids are believed to have been built during the Old Kingdom period of Ancient Egypt, over 4,500 years ago.\r\n<br><br>\r\nThe Giza complex consists of three main pyramids - the Great Pyramid of Giza, the Pyramid of Khafre, and the Pyramid of Menkaure - as well as several smaller pyramids, temples, and tombs. The Great Pyramid of Giza, built for the Pharaoh Khufu, is the largest of the three pyramids and is considered one of the Seven Wonders of the Ancient World.\r\n<br><br>\r\nVisitors to the Giza Pyramids can explore the complex and marvel at the incredible feats of engineering and architectural design that were accomplished so many centuries ago. The pyramids are made of millions of limestone blocks, some of which weigh as much as 80 tons, and were constructed using a system of ramps and pulleys.\r\n<br><br>\r\nIn addition to the pyramids themselves, visitors can also explore the surrounding area, which includes the Sphinx, a massive limestone statue of a mythical creature with the body of a lion and the head of a human. The Sphinx is believed to have been built during the reign of Pharaoh Khafre and is one of the most recognizable symbols of ancient Egypt.\r\n<br><br>\r\nVisitors can also learn about the history and culture of Ancient Egypt at the nearby Egyptian Museum in Cairo, which features an extensive collection of artifacts and treasures from throughout Egypt\'s long and storied history.\r\n<br><br>\r\nOverall, the Giza Pyramids are a breathtaking testament to the ingenuity and creativity of the ancient world, and a must-visit destination for anyone interested in history, architecture, or the mysteries of the past.', 5),
(14, 'Luxor Temple', 'images/luxortemple.jpg', 'Explore the mystique and grandeur of Luxor Temple, a marvel of Ancient Egyptian art and architecture!', '$75.00', '$90.00', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3595.148500920015!2d32.63647597458369!3d25.699506811173826!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x144915c41edadf61%3A0x7693895c346c7d81!2sLuxor%20Temple!5e0!3m2!1sen!2slb!4v1682974579067!5', 'Luxor Temple is a stunning ancient temple complex located on the east bank of the Nile River in Luxor, Egypt. The temple dates back to the New Kingdom period of Ancient Egypt, approximately 3,400 years ago, and was dedicated to the Theban triad of the god Amun, his wife Mut, and their son Khonsu.\r\n<br><br>\r\nThe temple is a magnificent example of ancient Egyptian architecture, with towering columns, ornate carvings, and beautifully preserved statues. Visitors can explore the complex, which includes a large courtyard, a hypostyle hall, and several smaller chapels and sanctuaries.\r\n<br><br>\r\nOne of the most impressive features of Luxor Temple is the Great Colonnade, which consists of 14 massive columns that stand over 15 meters tall and are decorated with intricate carvings and hieroglyphics. Visitors can also see the obelisk of Ramses II, which once stood in front of the temple and is now the only one of its pair still standing.\r\n<br><br>\r\nThe temple has a rich history, having been used by various pharaohs over the centuries and even serving as a Christian church during the Roman period. Visitors can learn about the temple\'s history and significance at the nearby Luxor Museum, which features an extensive collection of artifacts and exhibits related to Ancient Egypt.\r\n<br><br>\r\nOverall, Luxor Temple is a fascinating and awe-inspiring destination that provides a glimpse into the rich history and culture of Ancient Egypt. With its stunning architecture, intricate carvings, and deep spiritual significance, it is a must-visit destination for anyone interested in ancient history, art, or architecture.', 5),
(15, 'Sharm El-Sheikh', 'images/sharmelsheikh.jpg', 'Discover paradise in Sharm El Sheikh, where sun, sea, and sand meet in a breathtakingly beautiful location!', '$100.00', '$140.00', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d112785.34096186324!2d34.26635052769658!3d27.946685568298292!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14533bca3624d2e3%3A0xdd987e9c1945fd9c!2sSharm%20El-Sheikh%2C%20Qesm%20Sharm%20Ash%20Sheikh%2C%20South%20Sinai%20Governorate%2C%20Egypt!5e0!3m2!1sen!2slb!4v1683011491379!5m2!1sen!2slb', 'Sharm El Sheikh is a world-renowned resort town located on the southern tip of Egypt\'s Sinai Peninsula. Known for its stunning beaches, clear turquoise waters, and fantastic diving and snorkeling opportunities, Sharm El Sheikh has become a popular destination for tourists from around the world.\r\n<br><br>\r\nVisitors to Sharm El Sheikh can enjoy a wide range of activities, from relaxing on the beach to exploring the area\'s many historical and cultural attractions. Some of the most popular activities in the area include snorkeling and diving in the Red Sea, where visitors can explore the colorful coral reefs and exotic marine life that call the area home.\r\n<br><br>\r\nSharm El Sheikh is also home to several ancient historical sites, including the Monastery of St. Catherine, which is located at the foot of Mount Sinai and is believed to be the site where Moses received the Ten Commandments. Visitors can also explore the Colored Canyon, a stunning natural formation of towering, colorful cliffs that offer breathtaking views and opportunities for hiking and rock climbing.\r\n<br><br>\r\nFor those seeking a more luxurious experience, Sharm El Sheikh is home to many world-class resorts, spas, and golf courses, as well as numerous restaurants, cafes, and shopping centers. Visitors can also take a sunset camel ride or go on a desert safari to explore the surrounding desert landscape.\r\n<br><br>\r\nOverall, Sharm El Sheikh is a beautiful and exciting destination that offers something for everyone, whether you\'re looking for adventure, relaxation, or a bit of both. With its stunning natural beauty, rich history and culture, and wide range of activities and amenities, it\'s no wonder that Sharm El Sheikh has become such a popular vacation spot.', 5),
(16, 'Mount Fuji', 'images/img-5.jpg', 'Discover the majesty and beauty of Japan\'s Mount Fuji, an awe-inspiring natural wonder and iconic symbol of the country\'s rich cultural heritage!', '$120.00', '$150.00', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d13015.197565360902!2d138.71706364307974!3d35.36062456307376!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6019629a42fdc899%3A0xa6a1fcc916f3a4df!2sMount%20Fuji!5e0!3m2!1sen!2slb!4v1683043586264!5m2!1sen!2slb', 'Mount Fuji is an iconic volcanic mountain located in Japan, standing at 3,776 meters tall. It is Japan\'s highest mountain and one of the most recognizable landmarks in the country.\r\n<br><br>\r\nMount Fuji is an active volcano that last erupted in 1707, and it is now classified as a dormant volcano. The mountain is located in a national park that covers an area of over 1200 square kilometers, and it is a popular destination for tourists and hikers.\r\n<br><br>\r\nHiking to the summit of Mount Fuji is a popular activity for visitors, and the official climbing season runs from July to August. During this time, the mountain is busy with hikers from around the world, all seeking to reach the peak and enjoy the incredible views from the top.\r\n<br><br>\r\nFor those who prefer a more relaxed experience, there are also several observation points around the mountain that offer stunning views of Mount Fuji and the surrounding landscape. These include Lake Kawaguchi, which is located at the base of the mountain and offers panoramic views of the peak.\r\n<br><br>\r\nThe area around Mount Fuji is also known for its natural hot springs, or onsen, which offer a relaxing and rejuvenating experience for visitors. There are several hot spring resorts located in the area, where visitors can soak in the warm waters and take in the stunning scenery.\r\n<br><br>\r\nOverall, Mount Fuji is a must-visit destination for anyone traveling to Japan, with its iconic beauty, rich cultural significance, and opportunities for hiking and outdoor adventure. Whether you\'re climbing to the summit or simply admiring the view from afar, Mount Fuji is sure to leave a lasting impression on all who visit.', 6),
(17, 'Nara', 'images/nara.jpg', 'Step into Japan\'s ancient past in Nara, where history, culture, and nature come together to create an enchanting and unforgettable destination!', '$100.00', '$130.00', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d210039.39459980486!2d135.7272573427963!3d34.65809850185067!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x600137c578a70cc1%3A0x4afed9b0b9492622!2sNara%2C%20Japan!5e0!3m2!1sen!2slb!4v1682974693567!', 'Nara is a beautiful city located in the Kansai region of Japan, just a short train ride away from Kyoto and Osaka. It is known for its rich cultural heritage, beautiful temples and shrines, and friendly deer that roam freely around the city.\r\n<br><br>\r\nOne of the main attractions in Nara is the Nara Park, a large public park where over 1,000 tame deer live and interact with visitors. The deer are considered sacred in Japanese culture and are protected by the government. Visitors can feed and pet the deer, making for a unique and memorable experience.\r\n<br><br>\r\nAnother popular attraction in Nara is the Todaiji Temple, one of Japan\'s most famous and historic temples. The temple is home to the world\'s largest bronze statue of Buddha, as well as several other important cultural artifacts.\r\n<br><br>\r\nIn addition to Todaiji, Nara is home to several other beautiful temples and shrines, including the Kasuga Taisha Shrine and the Horyuji Temple, which is one of the oldest wooden buildings in the world.\r\n<br><br>\r\nThe city of Nara also has a charming old town area, with traditional Japanese-style buildings, shops, and restaurants. Visitors can wander the streets and sample local cuisine, such as mochi rice cakes and grilled eel.\r\n<br><br>\r\nOverall, Nara is a must-visit destination for anyone traveling to Japan, with its rich history, cultural significance, and unique natural attractions. Whether you\'re exploring the temples and shrines, interacting with the friendly deer, or simply enjoying the city\'s quaint atmosphere, Nara is sure to leave a lasting impression on all who visit.', 6),
(18, 'Kyoto', 'images/kyoto.jpg', 'Experience the captivating beauty and cultural richness of Kyoto, Japan, where every corner is a masterpiece, and every moment is a journey of discovery!', '$90.00', '$110.00', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d417835.04898554896!2d135.3892079591276!3d35.098311963799844!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6001a8d6cd3cc3f1%3A0xc0961d366bbb1d3d!2sKyoto%2C%20Japan!5e0!3m2!1sen!2slb!4v168297472713', 'Kyoto is a beautiful city located in the Kansai region of Japan, known for its rich cultural heritage, stunning temples and shrines, and beautiful natural scenery.\r\n<br><br>\r\nOne of the most iconic sights in Kyoto is the Fushimi Inari Shrine, a stunning shrine complex dedicated to the god of rice and prosperity. The shrine is known for its thousands of bright red torii gates that wind their way up the hillside, creating a beautiful and otherworldly atmosphere.\r\n<br><br>\r\nAnother popular attraction in Kyoto is the Kinkakuji Temple, also known as the Golden Pavilion, which is a stunning Buddhist temple covered in gold leaf. The temple is set in a beautiful garden, and visitors can take in the serene atmosphere and stunning views.\r\n<br><br>\r\nKyoto is also home to several other important temples and shrines, including the Kiyomizu-dera Temple and the Ginkakuji Temple. These historic sites offer visitors a glimpse into Japan\'s rich cultural heritage and are must-see destinations for anyone visiting Kyoto.\r\n<br><br>\r\nIn addition to its cultural attractions, Kyoto is also known for its beautiful natural scenery. The city is surrounded by mountains and forests, and visitors can explore the many hiking trails and outdoor activities available in the area.\r\n<br><br>\r\nFinally, Kyoto is also famous for its traditional Japanese cuisine, including kaiseki ryori, a multi-course meal featuring seasonal ingredients and beautifully presented dishes. Visitors can also sample local specialties like matcha tea, wagashi sweets, and yuba tofu.\r\n<br><br>\r\nOverall, Kyoto is a must-visit destination for anyone traveling to Japan, with its rich history, cultural significance, natural beauty, and delicious cuisine. Whether you\'re exploring the temples and shrines, hiking in the mountains, or sampling the local cuisine, Kyoto is sure to leave a lasting impression on all who visit.', 6),
(19, 'Petra', 'images/img-7.jpg', 'Experience the mesmerizing wonder of Petra, an ancient city of breathtaking beauty and mystery!', '$70.00', '$90.00', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d27552.521865959945!2d35.462555441336356!3d30.320662281876793!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x15016930021ab6b1%3A0xe43a697bc3a3e0b9!2sWadi%20Musa%2C%20Jordan!5e0!3m2!1sen!2slb!4v1682', 'Petra is a historical and archaeological city located in southern Jordan, known for its impressive rock-cut architecture and ancient history. The city was carved into the red sandstone cliffs by the Nabataean people more than 2,000 years ago, and was later inhabited by the Romans and other civilizations.\r\n<br><br>\r\nOne of the most iconic sights in Petra is the Treasury, also known as Al-Khazneh. This magnificent temple is carved into the sandstone cliffs and features intricate carvings and detailed facades. Visitors can take a short walk through the narrow canyon called the Siq to reach the Treasury, which is an unforgettable experience.\r\n<br><br>\r\nAnother popular attraction in Petra is the Monastery, a large and impressive temple located at the top of a hill. Visitors must climb up more than 800 steps to reach the Monastery, but the views and the temple itself are well worth the effort.\r\n<br><br>\r\nIn addition to the Treasury and the Monastery, Petra is home to many other impressive rock-cut buildings, including the Roman Theater, the Royal Tombs, and the Great Temple. Visitors can explore these ancient ruins on foot or by horse-drawn carriage.\r\n<br><br>\r\nPetra is also surrounded by beautiful desert landscapes, and visitors can take guided hikes or camel rides to explore the natural beauty of the area. The Wadi Rum desert, which was made famous by the movie Lawrence of Arabia, is also located nearby and is a popular destination for outdoor adventures.\r\n<br><br>\r\nOverall, Petra is a must-visit destination for anyone interested in ancient history and archaeology. Its impressive rock-cut architecture, stunning desert landscapes, and rich cultural heritage make it one of the most unique and unforgettable destinations in the world.', 7),
(20, 'Dead Sea', 'images/deadsea.jpg', 'Immerse yourself in the healing powers of the Dead Sea, a tranquil oasis that will rejuvenate your body and soul!', '$60.00', '$80.00', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d435269.2823105609!2d35.16061862474877!3d31.536756941327067!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x15033c2eaf9fbba1%3A0xf38cff48a0c15882!2sDead%20Sea!5e0!3m2!1sen!2slb!4v1683043820984!5m2!1sen!2slb', 'The Dead Sea is a natural wonder located between Jordan and Palestine, and is the lowest point on Earth at over 400 meters below sea level. It is famous for its high salt content, which allows people to float effortlessly in the water and is also known for its therapeutic and medicinal properties.\r\n<br><br>\r\nVisitors to the Dead Sea can relax on the beach, soak in the salty waters, or try a variety of spa treatments and mud baths that are said to have many health benefits. The minerals and salt in the water and mud are said to help with skin conditions, joint pain, and other health issues.\r\n<br><br>\r\nIn addition to the therapeutic properties of the Dead Sea, the surrounding area is also home to several important historical and religious sites. The ancient fortress of Masada is located nearby and offers stunning views of the surrounding desert landscape. The Dead Sea Scrolls, which are some of the oldest known texts of the Hebrew Bible, were discovered in caves near the Dead Sea and can be viewed at the palestinian Museum in Jerusalem.\r\n<br><br>\r\nVisitors to the Dead Sea can also explore the surrounding desert landscapes, take a dip in the Ein Gedi nature reserve, or visit the nearby city of Jericho, which is one of the oldest continuously inhabited cities in the world.\r\n<br><br>\r\nOverall, the Dead Sea is a unique and unforgettable destination that offers a combination of relaxation, history, and natural beauty. Whether you\'re floating in the salty waters, exploring the nearby historical sites, or taking in the stunning desert landscapes, a trip to the Dead Sea is sure to be a memorable experience.', 7),
(21, 'Wadi Rum', 'images/wadirum.jpg', 'Explore the mesmerizing beauty and rich culture of Wadi Rum, Jordan, on an unforgettable desert adventure!', '$65.00', '$75.00', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3482963.788937828!2d32.84862750497706!3d31.515045061099855!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x150093a5d3b537b3%3A0xe9885592958b5d07!2sWadi%20Rum%20Protected%20Area!5e0!3m2!1sen!2slb!4v', 'Wadi Rum is a desert valley in southern Jordan that is famous for its stunning red sandstone rock formations, towering cliffs, and ancient rock carvings. It is also known as the Valley of the Moon, thanks to its otherworldly and almost lunar landscape.\r\n<br><br>\r\nVisitors to Wadi Rum can take guided tours by jeep or camel, or even explore the desert on foot. The vast and empty landscapes are perfect for hiking, and there are a number of hiking trails that wind through the valley, including the popular trek up Jebel Um Ishrin, which offers breathtaking panoramic views of the surrounding desert.\r\n<br><br>\r\nWadi Rum is also a popular destination for adventure sports, including rock climbing and sandboarding. The towering cliffs and sand dunes offer a wide range of challenges for adventure seekers of all levels.\r\n<br><br>\r\nIn addition to its stunning natural beauty and adventure opportunities, Wadi Rum is also home to a rich cultural heritage. It has been inhabited by various civilizations over the centuries, including the Nabataeans, who left their mark in the form of ancient rock carvings and inscriptions. Visitors can also explore Bedouin culture by staying in a traditional Bedouin camp and learning about the local way of life.\r\n<br><br>\r\nOverall, Wadi Rum is a unique and unforgettable destination that offers a combination of natural beauty, adventure, and cultural heritage. Whether you\'re exploring the red sandstone cliffs, hiking through the desert, or learning about the local culture, a trip to Wadi Rum is sure to be an unforgettable experience.', 7),
(22, 'Baalbek', 'images/img-10.jpg', 'Marvel at the ancient ruins of Baalbek, Lebanon, a testament to the magnificence of ancient civilizations.', '$70.00', '$90.00', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d13230.10696029457!2d36.200740141849074!3d34.004687870793774!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1518a17d7177e915%3A0xc0d03df81962b370!2sBaalbek!5e0!3m2!1sen!2slb!4v1683043915216!5m2!1sen!2slb', 'Baalbek is a city located in the Beqaa Valley of Lebanon, known for its incredible ancient Roman ruins. The most famous attraction in Baalbek is the Temple of Jupiter, a massive structure with 54 columns, each over 19 meters tall, that was constructed in the 1st century AD. The temple is believed to have been the largest Roman temple ever built, and its ruins are a testament to the engineering and architectural prowess of the ancient Romans.\r\n<br><br>\r\nAnother notable structure in Baalbek is the Temple of Bacchus, a smaller but equally impressive temple dedicated to the Roman god of wine. It features intricate carvings and friezes that are incredibly well-preserved and offer a glimpse into the artistic and cultural traditions of the ancient Romans.\r\n<br><br>\r\nVisitors to Baalbek can also explore the ancient ruins of the city, which include other temples, public buildings, and residential areas. The ruins offer a fascinating glimpse into the history and culture of the region, and the area has been designated as a UNESCO World Heritage Site due to its outstanding historical and archaeological significance.\r\n<br><br>\r\nIn addition to its incredible historical attractions, Baalbek is also known for its scenic beauty and its position at the foothills of the Lebanon Mountains. Visitors can take in stunning views of the surrounding countryside, go hiking in the nearby mountains, or simply relax and enjoy the local cuisine and hospitality.\r\n<br><br>\r\nOverall, Baalbek is a fascinating and unique destination that offers a combination of history, culture, and natural beauty. Whether you\'re exploring the ancient ruins, taking in the stunning views, or experiencing the local culture and cuisine, a trip to Baalbek is sure to be a memorable and enriching experience.', 8),
(23, 'Jeita Grotto', 'images/jeitagrotto.jpg', 'Discover the awe-inspiring beauty of Jeita Grotto, a stunning cave system with an underground river!', '$70.00', '$85.00', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3309.9043411481434!2d35.63825302492336!3d33.94358837346113!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x151f17215880a78f%3A0x3df0a81262949b78!2sJeita%20Grotto!5e0!3m2!1sen!2slb!4v1682974917441!5', 'Jeita Grotto is a popular destination for travelers visiting Lebanon. Located about 20 kilometers north of Beirut, this natural wonder is a must-see attraction for anyone who loves the outdoors, natural beauty, and adventure.<br>\r\n<br>\r\nThe Jeita Grotto consists of two separate limestone caves, which are connected by an underground river. The lower cave is accessible by boat and is the longest water cave in the Middle East, while the upper cave can be explored on foot. The grotto is home to an incredible array of stalactites, stalagmites, and other unique rock formations, many of which have been naturally shaped by water over millions of years.<br>\r\n<br>\r\nTo reach the grotto, visitors must first take a cable car ride to the entrance of the cave. Once inside, they will be treated to an unforgettable experience as they explore the stunning natural wonders hidden deep beneath the earth\'s surface.<br>\r\n<br>\r\nJeita Grotto is open year-round, and visitors are advised to wear comfortable shoes and bring a light jacket or sweater, as the caves can be chilly. Guided tours are available in several languages, including English, French, and Arabic. Visitors can also enjoy a snack or a meal at the on-site restaurant or pick up souvenirs at the gift shop.<br>\r\n<br>\r\nOverall, a trip to Jeita Grotto is a must-do for anyone visiting Lebanon. It\'s an unforgettable experience that will leave you in awe of the natural world and its incredible beauty.', 8);
INSERT INTO `products` (`id`, `name`, `image`, `description`, `newprice`, `oldprice`, `map`, `details`, `catid`) VALUES
(24, 'Harissa', 'images/harissa.jpg', 'Take in the stunning views and rich history of Harissa, a hilltop sanctuary overlooking the Mediterranean!', '$75.00', '$90.00', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d13233.909674475226!2d35.64261314182734!3d33.98026897094166!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x151f40ca8b5ed947%3A0x8791c18842a56812!2sHarissa!5e0!3m2!1sen!2slb!4v1683044236914!5m2!1sen!2slb', 'Harissa is a small town located in the hills overlooking the Bay of Jounieh in Lebanon. It is a popular destination for both locals and tourists alike, thanks to its stunning views, historical attractions, and vibrant culture.\r\n<br><br>\r\nOne of the main attractions in Harissa is the iconic statue of Our Lady of Lebanon, a towering 15-ton bronze statue of the Virgin Mary that overlooks the town and the bay below. Visitors can take a cable car up to the statue and explore the surrounding area, which includes a church, a museum, and a variety of souvenir shops and restaurants.\r\n<br><br>\r\nIn addition to the statue of Our Lady of Lebanon, Harissa is also known for its stunning views of the bay and the surrounding mountains. Visitors can take scenic hikes through the hills, visit local wineries and vineyards, or simply relax and take in the beauty of the area.\r\n<br><br>\r\nFor those interested in history and culture, Harissa also offers a number of fascinating attractions. The town is home to a number of churches and monasteries, including the Monastery of St. Paul and the Monastery of St. Anthony, both of which date back to the 17th century. Visitors can also explore the nearby town of Jounieh, which is known for its lively nightlife, shopping, and dining scenes.\r\n<br><br>\r\nOverall, Harissa is a unique and charming destination that offers a combination of natural beauty, historical attractions, and vibrant culture. Whether you\'re exploring the iconic statue of Our Lady of Lebanon, taking in the stunning views of the bay, or experiencing the local history and culture, a trip to Harissa is sure to be a memorable and enriching experience.', 8),
(25, 'Great Wall Of China', 'images/img-8.jpg', 'Experience The Grandeur Of The Great Wall Of China And Take In The Stunning Scenery.', '$90.00', '$120.00', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3036.958774346302!2d116.5677999752556!3d40.43191175471643!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x35f121d7687f2ccf%3A0xd040259b950522df!2sGreat%20Wall%20of%20China!5e0!3m2!1sen!2slb!4v16829', 'The Great Wall of China is one of the world\'s most iconic landmarks and a must-see destination for anyone traveling to China. The wall is a series of fortifications that were constructed along the northern borders of China over many centuries, with the earliest sections dating back as far as the 7th century BC.\r\n<br><br>\r\nThe Great Wall stretches for over 13,000 miles and consists of many different sections, each with its own unique features and attractions. Some of the most popular sections for visitors include the Badaling section, which is the most well-preserved and easily accessible section of the wall, and the Mutianyu section, which is known for its stunning views and challenging hiking trails.\r\n<br><br>\r\nVisitors to the Great Wall can take in breathtaking views of the surrounding countryside and explore the many watchtowers, guardhouses, and other fortifications that were built along the wall. The wall is also home to a number of historical and cultural attractions, including ancient temples, monuments, and museums that offer insights into the history and culture of China.\r\n<br><br>\r\nIn addition to exploring the Great Wall itself, visitors can also experience the many other attractions and activities that the region has to offer. These include visiting the nearby Forbidden City and Tiananmen Square in Beijing, taking a boat ride on the nearby Ming Tombs reservoir, and trying local delicacies such as Peking duck and dumplings.\r\n<br><br>\r\nOverall, the Great Wall of China is a must-see destination for anyone interested in history, culture, and natural beauty. Whether you\'re exploring the wall itself, taking in the stunning views of the surrounding countryside, or experiencing the local culture and cuisine, a trip to the Great Wall is sure to be an unforgettable experience.', 9),
(26, 'Shanghai', 'images/shanghai.jpg', 'Discover the modern marvels and rich cultural heritage of Shanghai, China\'s bustling metropolis!', '$85.00', '$95.00', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1747234.747009073!2d119.10779880329717!3d31.204993132894526!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x35b27040b1f53c33%3A0x295129423c364a1!2sShanghai%2C%20China!5e0!3m2!1sen!2slb!4v1682975501', 'Shanghai is a vibrant and dynamic city located on the east coast of China. Known for its modern skyscrapers, historic landmarks, and thriving cultural scene, Shanghai offers something for everyone.\r\n<br><br>\r\nOne of the most popular attractions in Shanghai is the Bund, a historic waterfront area located along the Huangpu River. Here, visitors can take in stunning views of the city\'s iconic skyline, explore the many shops and restaurants, and stroll along the waterfront promenade.\r\n<br><br>\r\nAnother must-see attraction in Shanghai is the Shanghai Tower, one of the tallest buildings in the world. Visitors can take a high-speed elevator to the top of the tower and enjoy panoramic views of the city from the observation deck.\r\n<br><br>\r\nShanghai is also known for its vibrant art and cultural scene. Visitors can explore the many museums and galleries throughout the city, including the Shanghai Museum, which features a vast collection of Chinese art and artifacts. The city is also home to a thriving theater and music scene, with performances ranging from traditional Chinese opera to contemporary rock concerts.\r\n<br><br>\r\nFood lovers will also find plenty to enjoy in Shanghai, with a diverse array of local and international cuisine available throughout the city. Some popular local dishes include xiaolongbao (steamed soup dumplings) and shengjianbao (pan-fried pork buns).\r\n<br><br>\r\nOverall, Shanghai is a dynamic and exciting city that offers a wealth of attractions and experiences for visitors. Whether you\'re exploring the historic landmarks, taking in the stunning views from the Shanghai Tower, or experiencing the local art and culture, a trip to Shanghai is sure to be an unforgettable experience.', 9),
(27, 'Lhasa', 'images/lhasa.jpg', 'Explore the mystical beauty and rich culture of Lhasa, China, on a journey of a lifetime!', '$75.00', '$90.00', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d221902.4291189307!2d90.99302107826496!3d29.65523141451362!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x376133ca20bbf821%3A0x5851567ed41b17a4!2sLhasa%2C%20Tibet%2C%20China!5e0!3m2!1sen!2slb!4v1683008499299!5m2!1sen!2slb', 'Lhasa, the capital city of Tibet, is a spiritual and cultural hub that attracts visitors from around the world. Located high in the Himalayan Mountains, Lhasa is home to a number of historic and religious landmarks, as well as stunning natural beauty.\r\n<br><br>\r\nOne of the most popular attractions in Lhasa is the Potala Palace, a towering fortress that was once the residence of the Dalai Lama. The palace features a stunning array of murals, sculptures, and other religious artifacts, and offers breathtaking views of the city below.\r\n<br><br>\r\nAnother must-see attraction in Lhasa is the Jokhang Temple, one of the holiest sites in Tibetan Buddhism. The temple features a stunning collection of religious art and artifacts, and is a popular destination for pilgrims and tourists alike.\r\n<br><br>\r\nVisitors to Lhasa can also explore the many markets and bazaars throughout the city, which offer a wide variety of Tibetan handicrafts, textiles, and other goods. The Barkhor Street market, located in the heart of the old city, is particularly popular and offers a unique glimpse into Tibetan culture and daily life.\r\n<br><br>\r\nFor those interested in outdoor activities, Lhasa also offers plenty of opportunities for hiking, trekking, and other adventures. The nearby Namtso Lake, one of the highest lakes in the world, is a popular destination for nature lovers and offers stunning views of the surrounding mountains and landscapes.\r\n<br><br>\r\nOverall, Lhasa is a unique and fascinating destination that offers a wealth of cultural, spiritual, and natural attractions. Whether you\'re exploring the historic landmarks, shopping for Tibetan handicrafts, or taking in the breathtaking views of the Himalayas, a trip to Lhasa is sure to be an unforgettable experience.', 9),
(28, 'Burj Khalifa', 'images/img-9.jpg', 'Get ready to reach new heights at Burj Khalifa, the world\'s tallest building and an iconic symbol of Dubai\'s modern architecture and engineering feats!', '$160.00', '$190.00', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3610.1786555706963!2d55.269762970857606!3d25.197196928449934!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3e5f43348a67e24b%3A0xff45e502e1ceb7e2!2sBurj%20Khalifa!5e0!3m2!1sen!2slb!4v1683009704234!5m2!1sen!2slb', 'Burj Khalifa, located in Dubai, is the tallest building in the world and a must-visit attraction for anyone visiting the city. Standing at 828 meters tall, the Burj Khalifa is an engineering marvel that offers stunning views of the city and the surrounding landscape.\r\n<br><br>\r\nVisitors can take an elevator ride to the observation deck on the 124th floor, known as At the Top, where they can enjoy panoramic views of Dubai and beyond. The observation deck features interactive exhibits that provide information about the building\'s construction and the city\'s history.\r\n<br><br>\r\nFor those looking for an even more luxurious experience, the Burj Khalifa also features the world\'s highest restaurant, At.mosphere, located on the 122nd floor. Visitors can enjoy a gourmet meal while taking in the breathtaking views of the city.\r\n<br><br>\r\nIn addition to its observation deck and restaurant, the Burj Khalifa is also home to residential apartments, offices, and a luxury hotel. The building\'s unique design and impressive height make it a popular subject for photographers, and the nightly light show that illuminates the building is a must-see for anyone visiting Dubai.\r\n<br><br>\r\nOverall, a visit to the Burj Khalifa is a once-in-a-lifetime experience that offers unparalleled views of Dubai and the surrounding landscape. Whether you\'re looking to dine in the world\'s highest restaurant, take in the stunning views from the observation deck, or simply marvel at the engineering feat that is the Burj Khalifa, a visit to this iconic building is sure to be unforgettable.', 10),
(29, 'Dubai Miracle Garden', 'images/dubaimiraclegarden.jpg', 'Escape to a breathtaking oasis at Dubai Miracle Garden, featuring over 45 million flowers in stunning displays and intricate designs that will leave you in awe!', '$100.00', '$110.00', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3595.1486468882194!2d32.63647597421424!3d25.69950197739101!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x144915c41edadf61%3A0x7693895c346c7d81!2sLuxor%20Temple!5e0!3m2!1sen!2slb!4v1683009814609!5m2!1sen!2slb', 'Dubai Miracle Garden is a stunning floral paradise located in Dubai, United Arab Emirates. It is one of the world\'s largest flower gardens and is home to over 45 million flowers, including a variety of colorful blooms, sculptures, and structures.\r\n<br><br>\r\nThe garden is spread over an area of 72,000 square meters and features a variety of themed gardens, including the heart-shaped flower beds, the Emirates A380 floral structure, and the world\'s largest flower arrangement in the shape of a Disney character. The garden also features a butterfly garden, a floral clock, and a 3D flower display.\r\n<br><br>\r\nVisitors can enjoy a leisurely walk through the gardens, taking in the beautiful sights and scents of the various flowers. There are also plenty of photo opportunities throughout the garden, with several areas set up specifically for taking pictures.\r\n<br><br>\r\nThe Dubai Miracle Garden is open from November to May, when the weather is cooler and more conducive to enjoying the outdoor garden. There are also several cafes and food stalls located throughout the garden, providing visitors with a variety of dining options.\r\n<br><br>\r\nOverall, the Dubai Miracle Garden is a must-see attraction for anyone visiting Dubai who appreciates natural beauty and stunning floral displays. The garden is a true testament to human creativity and imagination and offers a unique experience that is both relaxing and awe-inspiring.', 10),
(30, 'Yas Island', 'images/yasisland.jpg', 'Experience paradise on Yas Island: a stunning blend of luxurious resorts, thrilling theme parks, and pristine beaches.', '$90.00', '$100.00', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d58095.81985430544!2d54.56177824107479!3d24.485846962643482!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3e5e457d9c174315%3A0xbea25f33cf37e48e!2sYas%20Island!5e0!3m2!1sen!2slb!4v1683009774505!5m2!1sen!2slb', 'Yas Island is a man-made island located in Abu Dhabi, United Arab Emirates, and is one of the country\'s top tourist destinations. The island features a wide range of entertainment and leisure options, including world-class theme parks, luxury hotels, shopping malls, restaurants, and more.\r\n<br><br>\r\nOne of the island\'s biggest attractions is Ferrari World Abu Dhabi, a massive indoor theme park that is dedicated to the legendary Italian sports car brand. The park features a variety of thrilling rides and attractions, including the world\'s fastest roller coaster, the Formula Rossa, which reaches speeds of up to 240 km/h.\r\n<br><br>\r\nAnother major attraction on Yas Island is the Yas Waterworld, an outdoor water park that features over 40 rides, slides, and attractions, including the world\'s first hydro-magnetic tornado water slide. Visitors can also relax on the island\'s beaches, go shopping at the Yas Mall, or enjoy a round of golf at the Yas Links Abu Dhabi.\r\n<br><br>\r\nFor those looking for a luxurious stay, Yas Island features several high-end hotels, including the Yas Viceroy Abu Dhabi, which is built over the Yas Marina Circuit Formula 1 race track and features stunning views of the track and the surrounding area.\r\n<br><br>\r\nOverall, Yas Island is a great destination for anyone looking for a fun and exciting vacation in Abu Dhabi. With its world-class theme parks, luxurious hotels, and stunning natural beauty, the island has something to offer for visitors of all ages and interests.', 10),
(31, 'Machu Picchu', 'images/img-11.jpg', 'Embark On An Unforgettable Journey Along The Inca Trail In Peru, And Discover The Magic Of Machu Picchu.', '$90.00', '$100.00', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3883.9838385620574!2d-72.49989642619838!3d-13.226330787112936!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x916d9a5f89555555%3A0x3a10370ea4a01a27!2sMachu%20Picchu!5e0!3m2!1sen!2slb!4v1683009918113!5m2!1sen!2slb', 'Machu Picchu is a world-famous ancient Incan city located high in the Andes Mountains of Peru. The city was built in the 15th century and abandoned just 100 years later, but its unique architecture and stunning setting have made it one of the most popular tourist destinations in the world.\r\n<br><br>\r\nThe city is located on a ridge overlooking the Urubamba River valley and is surrounded by towering mountains and lush forests. Its buildings were constructed from polished stone blocks that were carefully cut to fit together without the use of mortar. The city\'s most famous structures include the Temple of the Sun, the Intihuatana stone, and the Room of the Three Windows.\r\n<br><br>\r\nVisitors can reach Machu Picchu by hiking the Inca Trail, which takes several days and offers stunning views of the surrounding mountains and valleys. Alternatively, visitors can take a train to the nearby town of Aguas Calientes and then hike or take a bus up to the site.\r\n<br><br>\r\nOnce at Machu Picchu, visitors can explore the ruins on their own or hire a guide to learn more about the history and significance of the site. There are also several hiking trails in the area that offer stunning views of the surrounding mountains and valleys.\r\n<br><br>\r\nOverall, Machu Picchu is a must-see destination for anyone visiting Peru or South America. Its stunning natural setting, unique architecture, and rich history make it one of the most fascinating and awe-inspiring sites in the world.', 11),
(32, 'Huacachina', 'images/huacachina.jpg', 'Enjoy the serene oasis views in the heart of the Peruvian desert with a tour of Huacachina!', '$80.00', '$105.00', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3869.8251021050487!2d-75.76568357617813!3d-14.087499636340283!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9110e3010800b101%3A0x136be001d08a4223!2sHuacachina%2011000%2C%20Peru!5e0!3m2!1sen!2slb!4v1683009961634!5m2!1sen!2slb', 'Huacachina is a small desert oasis located in southwestern Peru, just a few miles from the city of Ica. The oasis is surrounded by towering sand dunes and is a popular destination for adventure-seekers and tourists looking to experience the beauty of the Peruvian desert.\r\n<br><br>\r\nLegend has it that Huacachina was created when a beautiful Incan princess was bathing in a nearby river and was surprised by a hunter. As she fled, the water that covered her body turned into the oasis that we see today. Nowadays, Huacachina is a popular tourist destination and attracts visitors from all over the world.\r\n<br><br>\r\nOne of the main attractions in Huacachina is sandboarding, which involves riding down the towering sand dunes on a board. Visitors can also take a dune buggy tour of the area or go on a camel ride through the desert. There are also several restaurants and bars in the area where visitors can relax and enjoy the stunning desert views.\r\n<br><br>\r\nIn addition to its outdoor activities, Huacachina also has a rich history and culture. Visitors can explore the nearby city of Ica and learn about the region\'s history and visit local museums, such as the Regional Museum of Ica. They can also visit the local vineyards and try the famous Peruvian pisco, a type of brandy that is made from fermented grapes.\r\n<br><br>\r\nOverall, Huacachina is a unique and beautiful destination that offers a mix of outdoor adventure, culture, and history. Whether you\'re looking to sandboard down towering dunes or explore the local vineyards, Huacachina is a must-see destination for anyone visiting Peru.', 11),
(33, 'Arequipa', 'images/arequipa.jpg', 'Explore the colonial beauty and cultural richness of Arequipa, Peru, on an unforgettable journey of discovery!', '$75.00', '$90.00', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d61238.541868151435!2d-71.58021158168084!3d-16.404048336943237!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x91424a487785b9b3%3A0xa3c4a612b9942036!2sArequipa%2C%20Peru!5e0!3m2!1sen!2slb!4v1683010002554!5m2!1sen!2slb', 'Arequipa is a beautiful city located in southern Peru, known for its colonial architecture, stunning natural scenery, and rich cultural heritage. The city is surrounded by three volcanoes, including Misti, Chachani, and Pichu Pichu, which offer breathtaking views of the Andes Mountains.\r\n<br><br>\r\nOne of the main attractions in Arequipa is the historic center, which was declared a UNESCO World Heritage Site in 2000. The center features colonial-era buildings, such as the Santa Catalina Monastery, which was founded in the 16th century and is considered one of the most beautiful religious buildings in South America. Other notable landmarks include the Plaza de Armas, the Cathedral of Arequipa, and the Compañia de Jesus Church.\r\n<br><br>\r\nIn addition to its historic attractions, Arequipa is also known for its cuisine, which is a mix of Spanish, indigenous, and African influences. Visitors can try local dishes, such as rocoto relleno, a spicy stuffed pepper dish, and chupe de camarones, a hearty shrimp soup. The city is also famous for its picanterías, traditional restaurants that serve local dishes and drinks.\r\n<br><br>\r\nOutside of the city, visitors can explore the nearby Colca Canyon, one of the deepest canyons in the world, which is home to the Andean condor and other unique wildlife. They can also visit the Salinas and Aguada Blanca National Reserve, a protected area that features a diverse range of flora and fauna.\r\n<br><br>\r\nOverall, Arequipa is a fascinating destination that offers a mix of history, culture, and natural beauty. Whether you\'re exploring the city\'s historic center, trying local cuisine, or venturing out into the surrounding countryside, Arequipa is a must-see destination for anyone visiting Peru.', 11),
(34, 'Santorini', 'images/santorini.jpg', 'Escape to the enchanting island of Santorini, Greece, where the breathtaking views create a truly magical and unforgettable experience!', '$120.00', '$150.00', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d12842.15957277748!2d25.421870694070446!3d36.42032580772081!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1499cdce05e3bce9%3A0x9f4c192bbefa1db!2sThera%20847%2000%2C%20Greece!5e0!3m2!1sen!2slb!4v1683010059109!5m2!1sen!2slb', 'Santorini is a picturesque island located in the Aegean Sea, in the Cyclades archipelago of Greece. Known for its whitewashed buildings, stunning views of the Mediterranean, and beautiful beaches, Santorini is a popular destination for travelers from around the world.\r\n<br><br>\r\nThe island is famous for its unique architecture, which features traditional white-washed buildings with blue roofs and doors. Visitors can explore the charming towns of Oia, Fira, and Imerovigli, which offer breathtaking views of the Mediterranean Sea and the island\'s rugged coastline.\r\n<br><br>\r\nOne of the top attractions in Santorini is the caldera, a massive volcanic crater that was formed by a volcanic eruption over 3,000 years ago. Visitors can take a boat tour of the caldera or hike the trail that winds around its edge, which offers stunning views of the island\'s unique landscape.\r\n<br><br>\r\nSantorini is also known for its beautiful beaches, including the black sand beaches of Perissa and Kamari and the red sand beach of Akrotiri. Visitors can swim, sunbathe, or enjoy water sports like windsurfing, kayaking, and stand-up paddleboarding.\r\n<br><br>\r\nFinally, Santorini is a popular destination for food and wine enthusiasts, offering a wide range of traditional Greek dishes, fresh seafood, and local wines. Visitors can sample local specialties like fava, a traditional yellow split pea puree, and tomatokeftedes, tomato fritters that are a Santorini specialty.\r\n<br><br>\r\nOverall, Santorini is a must-visit destination for anyone looking to experience the beauty and culture of Greece. Whether you\'re exploring the island\'s charming towns, relaxing on its beautiful beaches, or indulging in its delicious cuisine, Santorini is sure to be a highlight of your trip to Greece.', 12),
(35, 'Mykonos', 'images/mykonos.jpg', 'Discover the Mediterranean charm and allure of Mykonos, Greece, where sun-kissed beaches, charming streets, and endless fun await!', '$110.00', '$135.00', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d101356.61373613021!2d25.298445662579258!3d37.451414045144276!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14a2b8b4f03c9b91%3A0x78d164471e79b4a1!2sMykonos!5e0!3m2!1sen!2slb!4v1683010104605!5m2!1sen!2slb', 'Mykonos is a beautiful island located in the Aegean Sea, in the Cyclades archipelago of Greece. Known for its vibrant nightlife, stunning beaches, and charming white-washed buildings, Mykonos is a popular destination for travelers from around the world.\r\n<br><br>\r\nOne of the top attractions in Mykonos is its beautiful beaches, which are famous for their crystal clear waters and stunning natural scenery. Some of the most popular beaches on the island include Paradise Beach, Super Paradise Beach, and Psarou Beach, all of which offer a range of water sports and activities for visitors to enjoy.\r\n<br><br>\r\nMykonos is also known for its charming white-washed buildings, which can be found in the island\'s main town, Chora. Visitors can explore the narrow streets of Chora, which are lined with shops, restaurants, and cafes, or visit the island\'s famous windmills, which date back to the 16th century.\r\n<br><br>\r\nAnother highlight of Mykonos is its vibrant nightlife, which includes a range of bars, clubs, and restaurants that stay open until the early hours of the morning. Some of the most popular spots on the island include the Scandinavian Bar, the Tropicana Beach Bar, and the Cavo Paradiso club, which has hosted some of the biggest names in electronic music.\r\n<br><br>\r\nFinally, Mykonos is a popular destination for food and wine enthusiasts, offering a wide range of traditional Greek dishes, fresh seafood, and local wines. Visitors can sample local specialties like louza, a cured meat made from pork, and kopanisti, a spicy cheese spread that is a Mykonos specialty.\r\n<br><br>\r\nOverall, Mykonos is a must-visit destination for anyone looking to experience the beauty, culture, and nightlife of Greece. Whether you\'re relaxing on its beautiful beaches, exploring its charming towns, or enjoying its vibrant nightlife, Mykonos is sure to be a highlight of your trip to Greece.', 12),
(36, 'Meteora', 'images/meteora.jpg', 'Experience the wonder and spiritual serenity of Meteora, where towering rock formations and stunning vistas transport you to a world of peace and tranquility!', '$90.00', '$110.00', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3068.7987902908876!2d21.62801467496594!3d39.721704371559795!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x13590faee8327f39%3A0x7127add4d8bc32ff!2sMeteora!5e0!3m2!1sen!2slb!4v1683010144092!5m2!1sen!2slb', 'Meteora is a unique destination located in central Greece, known for its stunning landscape of towering rock formations and ancient monasteries perched on top of them. The word \"meteora\" means \"suspended in the air\" in Greek, and it\'s easy to see why when you visit this incredible site.\r\n<br><br>\r\nThe Meteora rocks were formed millions of years ago by a combination of natural geological processes, and they are now home to six active monasteries that date back to the 14th and 15th centuries. These monasteries were built by hermit monks who sought solitude and isolation, and they can only be reached by climbing steep steps or using a system of ropes and pulleys.\r\n<br><br>\r\nToday, Meteora is a popular tourist destination that attracts visitors from around the world. Visitors can explore the monasteries, which are filled with ancient religious artifacts and stunning frescoes, and enjoy panoramic views of the surrounding landscape from their vantage points high above the ground.\r\n<br><br>\r\nIn addition to the monasteries, Meteora is also a popular destination for rock climbing and hiking, with a network of trails and routes that wind their way through the stunning landscape. Visitors can also explore the nearby town of Kalambaka, which is home to a number of traditional Greek tavernas and restaurants serving local specialties like moussaka and pastitsio.\r\n<br><br>\r\nOverall, Meteora is a must-visit destination for anyone interested in history, religion, or natural beauty. Its stunning landscape and ancient monasteries offer a unique glimpse into the history and culture of Greece, and its network of hiking trails and climbing routes provide ample opportunities for adventure and exploration.', 12);

-- --------------------------------------------------------

--
-- Table structure for table `reviews`
--

CREATE TABLE `reviews` (
  `id` int(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `image` varchar(255) NOT NULL,
  `review` longtext NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `reviews`
--

INSERT INTO `reviews` (`id`, `name`, `image`, `review`) VALUES
(1, 'Jude Thorn', 'images/pic-1.jpg', 'An incredible adventure! I loved exploring new cultures and experiencing new things. Would definitely recommend for anyone looking to broaden their horizons.\r\n                '),
(2, 'Roy Smith', 'images/pic-2.jpg', 'Traveling is the perfect way to escape the mundane and see the world in a new light. Can\'t wait to plan my next trip!'),
(3, 'Marsha Singer', 'images/pic-3.jpg', 'Exploring exotic destinations is a dream come true. From stunning landscapes to unique cuisines, every moment was unforgettable.'),
(4, 'Tim Shaw', 'images/pic-4.jpg', 'Traveling allowed me to step out of my comfort zone and learn more about myself. It\'s an experience that everyone should have at least once in their lifetime.'),
(5, 'Lindsay Spice', 'images/pic-5.jpg', 'I had the opportunity to meet amazing people and make lifelong memories while traveling. It\'s an experience that has enriched my life in countless ways.'),
(6, 'Ann Black', 'images/pic-6.jpg', 'Exploring new destinations always leaves me feeling inspired and refreshed. There\'s nothing quite like the thrill of discovering something new.');

-- --------------------------------------------------------

--
-- Table structure for table `user_form`
--

CREATE TABLE `user_form` (
  `id` int(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `cpassword` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `user_form`
--

INSERT INTO `user_form` (`id`, `name`, `email`, `password`, `cpassword`) VALUES
(1, 'ghida', 'ghidagh@gmail.com', '1qaz2wsx3edc', 'ed'),
(2, 'bahaa', 'ghidagh@gmail.com', '1qaz2wsx3edc', 'fg'),
(3, 'bahaa', 'fg@gmail.com', '1234567890', 'hnkj'),
(4, 'asdcasc', 'ghidagh@gmail.com', 'aaaaaaaa1', 'aaaaaaaa1'),
(5, 'aaa', 'gh@gmail.com', 'bbbbbbbb1', 'bbbbbbbb1'),
(6, 'abc', 'abc@gmail.com', '1234567890', '1234567890'),
(7, 'ghada', 'ghada@gmail.com', '1qaz2wsx', '1qaz2wsx'),
(8, 'jhg', 'jhg@gmail.com', '94b06ab80d1573af035129e2f057db13', '94b06ab80d1573af035129e2f057db13'),
(9, 'houssam', 'houssam@gmail.com', '8853a57d9357609764fdb006f712921a', '8853a57d9357609764fdb006f712921a'),
(10, 'hani', 'Hani@Gmail.Com', 'zxcvbnm123', 'zxcvbnm123'),
(11, 'mimi', 'mimi@gmail.com', '4rfv5tgb', '4rfv5tgb');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `book_form`
--
ALTER TABLE `book_form`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `category`
--
ALTER TABLE `category`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `reviews`
--
ALTER TABLE `reviews`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `user_form`
--
ALTER TABLE `user_form`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `book_form`
--
ALTER TABLE `book_form`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

--
-- AUTO_INCREMENT for table `category`
--
ALTER TABLE `category`
  MODIFY `id` int(255) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=13;

--
-- AUTO_INCREMENT for table `products`
--
ALTER TABLE `products`
  MODIFY `id` int(255) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=37;

--
-- AUTO_INCREMENT for table `reviews`
--
ALTER TABLE `reviews`
  MODIFY `id` int(255) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;

--
-- AUTO_INCREMENT for table `user_form`
--
ALTER TABLE `user_form`
  MODIFY `id` int(255) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=12;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
